version: "3.9"
services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_PASSWORD: dbpasswd
      POSTGRES_USER: postgres
      POSTGRES_DB: clinic_scheduling
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./../../src/main/resources/db/migration/V1__create_tables.sql:/docker-entrypoint-initdb.d/01_create_table.sql
      - ./db_dump/inital_load.sql:/docker-entrypoint-initdb.d/02_initial_load.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5